name: Build OpenSSL & cURL for Android

on:
  workflow_dispatch:
  push:
    tags:
      - "v*.*.*"

jobs:
  get_versions:
    runs-on: ubuntu-latest
    outputs:
      openssl_version: ${{ steps.extract.outputs.openssl_version }}
      curl_version: ${{ steps.extract.outputs.curl_version }}
    steps:
      - name: Extract versions
        id: extract
        run: |
          echo "openssl_version=3.3.2" >> $GITHUB_OUTPUT
          echo "curl_version=8.9.0" >> $GITHUB_OUTPUT

  Compile_OpenSSL_for_Android:
    name: OpenSSL ${{ matrix.ANDROID_TARGET_ABI }} (NDK ${{ matrix.ANDROID_NDK }})
    needs: get_versions
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ANDROID_TARGET_ABI: [armeabi-v7a, arm64-v8a, x86, x86_64, riscv64]
        ANDROID_NDK: [r24b, r25c, r26d, r27c]
        include:
          - ANDROID_TARGET_ABI: riscv64
            ANDROID_TARGET_API: "35"
          - ANDROID_TARGET_ABI: armeabi-v7a
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: arm64-v8a
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: x86
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: x86_64
            ANDROID_TARGET_API: "21"
    env:
      OPENSSL_VERSION: ${{ needs.get_versions.outputs.openssl_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build OpenSSL
        run: |
          mkdir -p build/openssl
          echo "Fake build OpenSSL $OPENSSL_VERSION for ${{ matrix.ANDROID_TARGET_ABI }} NDK ${{ matrix.ANDROID_NDK }}" > build/openssl/README.txt

      - name: Package artifact
        run: |
          ART=OpenSSL_${OPENSSL_VERSION}_${{ matrix.ANDROID_TARGET_ABI }}_NDK-${{ matrix.ANDROID_NDK }}.tar.gz
          tar -C build/openssl -czf $ART .
          echo "ARTIFACT=$ART" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OpenSSL-${{ matrix.ANDROID_TARGET_ABI }}-NDK-${{ matrix.ANDROID_NDK }}
          path: ${{ env.ARTIFACT }}

  Compile_cURL_for_Android:
    name: cURL ${{ matrix.ANDROID_TARGET_ABI }} (NDK ${{ matrix.ANDROID_NDK }})
    needs: [get_versions, Compile_OpenSSL_for_Android]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        ANDROID_TARGET_ABI: [armeabi-v7a, arm64-v8a, x86, x86_64, riscv64]
        ANDROID_NDK: [r24b, r25c, r26d, r27c]
        include:
          - ANDROID_TARGET_ABI: riscv64
            ANDROID_TARGET_API: "35"
          - ANDROID_TARGET_ABI: armeabi-v7a
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: arm64-v8a
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: x86
            ANDROID_TARGET_API: "21"
          - ANDROID_TARGET_ABI: x86_64
            ANDROID_TARGET_API: "21"
    env:
      CURL_VERSION: ${{ needs.get_versions.outputs.curl_version }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build cURL
        run: |
          mkdir -p build/curl
          echo "Fake build cURL $CURL_VERSION for ${{ matrix.ANDROID_TARGET_ABI }} NDK ${{ matrix.ANDROID_NDK }}" > build/curl/README.txt

      - name: Package artifact
        run: |
          ART=cURL_${CURL_VERSION}_${{ matrix.ANDROID_TARGET_ABI }}_NDK-${{ matrix.ANDROID_NDK }}.tar.gz
          tar -C build/curl -czf $ART .
          echo "ARTIFACT=$ART" >> $GITHUB_ENV

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: cURL-${{ matrix.ANDROID_TARGET_ABI }}-NDK-${{ matrix.ANDROID_NDK }}
          path: ${{ env.ARTIFACT }}

  Publish_Release:
    name: Publish Release
    needs: [get_versions, Compile_OpenSSL_for_Android, Compile_cURL_for_Android]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Collect & package final zips
        run: |
          OPENSSL_VERSION=${{ needs.get_versions.outputs.openssl_version }}
          CURL_VERSION=${{ needs.get_versions.outputs.curl_version }}
          NDK_LIST=(r24b r25c r26d r27c)
          ABI_LIST=(armeabi-v7a arm64-v8a x86 x86_64 riscv64)

          > zips.txt

          for NDK in "${NDK_LIST[@]}"; do
            mkdir -p Output/$NDK
            for ABI in "${ABI_LIST[@]}"; do
              mkdir -p Output/$NDK/$ABI/openssl
              mkdir -p Output/$NDK/$ABI/curl

              # Artifact OpenSSL
              OPENSSL_ART="artifacts/OpenSSL_${OPENSSL_VERSION}_${ABI}_NDK-${NDK}.tar.gz"
              if [[ -f "$OPENSSL_ART" ]]; then
                tar -xzf "$OPENSSL_ART" -C Output/$NDK/$ABI/openssl
              fi

              # Artifact cURL
              CURL_ART="artifacts/cURL_${CURL_VERSION}_${ABI}_NDK-${NDK}.tar.gz"
              if [[ -f "$CURL_ART" ]]; then
                tar -xzf "$CURL_ART" -C Output/$NDK/$ABI/curl
              fi
            done

            # Tạo zip cho từng NDK
            FINAL_NAME="OpenSSL-${OPENSSL_VERSION}_cURL-${CURL_VERSION}_NDKs-${NDK}.zip"
            cd Output/$NDK
            zip -r "../../$FINAL_NAME" .
            cd ../..
            echo "$FINAL_NAME" >> zips.txt
          done

          # Xuất danh sách zip ra env
          echo "ZIP_LIST=$(cat zips.txt | tr '\n' ' ')" >> $GITHUB_ENV

